app = "casagan-pigery"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_URL = "https://casagan-pigery.fly.dev"
  LOG_CHANNEL = "errorlog"
  LOG_LEVEL = "error"
  SESSION_DRIVER = "cookie"
  CACHE_STORE = "file"
  QUEUE_CONNECTION = "sync"
  BROADCAST_CONNECTION = "log"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
